### PR TITLE
Adding AWS mockups for new region selection

### PR DESCRIPTION
**Pull request by blomquisg**
This is the result of a discussion regarding how to select the list of regions in AWS when creating/editing an AWS provider.

There are two problems going on here:

1) How to capture the correct regions and place them in the correct MIQ zones.

    We have two ways of capturing the AWS Regions from users.  And, those represent opposite ends of the spectrum.  First, the user can "discover" and AWS provider.  MIQ will find all regions where the user has VMs running, and create `CloudManagers` in MIQ for those regions.  Second, the user can "Create new cloud provider", and add a single region.  However, after adding this single region, the user cannot add additional regions to this account.

2) How to convey that S3 (and, in the future, other AWS services) are not region-bound.

  When a user adds an AWS provider, MIQ creates a `CloudManager` for the specific region or regions.  The user will see Cloud Managers like "AWS us-east-1" and "AWS us-west-1".  But, now that we're attempting to support S3, we're realizing that this approach of binding Managers to Regions is going to fall short of representing the actual service interactions.  In AWS, EC2 (i.e., Cloud Managers) are region-bound, but S3 can see all regions even if the buckets in S3 are region-bound.  This allows S3 to see all of the buckets used by any VM in any EC2 region regardless of the VM's region.

This design is supposed to address the problem in three ways.

* Show the list of managed regions on the AWS Cloud Provider add/edit page.  And, allow the user to select the list of regions that should be managed from that one page.

* Allow the user to select S3 in a region-agnostic way when adding regions to the provider.

* Allow the user to designate the correct zone for each region/manager.

This isn't an excellent approach.  Since, imo, there's still the problem of mixing region-bound services like EC2 with regionless services like S3.

This is a back of the napkin design at this point.  I'm very happy to hear criticisms and other ideas of how to solve the problem.

### CODE REVIEW

**Comment by blomquisg** [comment]
/cc @serenamarie125 

We're looking for short term and long term plans around this ... any feedback you have is appreciated

**Comment by miha-plesko** [comment]
I've played around problem 1 a week ago and came up with https://github.com/ManageIQ/manageiq-providers-amazon/pull/137 where Provider creates CloudManagers for a given list of regions and a single S3.

From my experience, the backend part is quite doable - a bunch of delegates and a helper function for creating cloud managers. Mixing cloud manager's and umbrella provider's **frontend**, however, is a bit more tricky. The logic at `/ems_cloud/new` is tightly bound to editing single manager as one could already guess from relevant filenames:

* app/controllers/ems_common.rb
* app/controllers/mixins/ems_common_angular.rb
* ...

Therefore we might want to avoid messing with cloud manager's page. Instead, we could make use of "Configuration -> Management" page. See screenshot below:

capture

User could come to this page and create umbrella provider for her AWS credentials specifying what managers does she want. Here she would be offered a [table that @blomquisg has shown](https://github.com/ManageIQ/manageiq-design/pull/23/files#diff-bb64751354dbe3fb8b9a6de3f5fe0b59) and a checkbox whether she wants S3 or not. On "Compute ->Clouds -> Providers" page user would then be prohibited from editing managers that are controlled by umbrella provider.

**Comment by gberginc** [comment]
@miha-plesko I don't think _configuration management_ is the way to go. It's currently used by Foreman, a management tool for all kinds of stuff, including configuration management. In my opinion, if provider is to become an umbrella for all kinds of stuff, it should properly be represented in the UI (separated set of views supporting listing, creation, editing, ...).

@blomquisg my biggest concern with the proposed approach is that

 * it overly complicates the creation of the manager: as an AWS user I am interested in managing my resources there, but all of the sudden I have to go over rather complex linking between AWS regions and MIQ zones
 * all of this happens when I am trying to create a new "compute cloud manager": in case I choose more than one region, this is actually going to create me several cloud managers (along with network + storage managers) which is going to cause confusion

Please, keep in mind that when I log into AWS, a region is a conveniently simple choice I have to make in the upper right corner of the AWS console. So I think this is more a question from the business and end-user perspective, but here are the two options that I find acceptable at the moment:

1. we keep the same "create new cloud manager" view that we have today, but only create region-dependent managers in the background (EC2, network, EBS storage manager). This makes sense, because these things are also separated in the AWS console in a similar manner. If users need more than one region, they will simply create managers for all regions they are interested in (I would assume that 2 or 3 regions at max allow most businesses to scale properly and ensure fallback mechanisms). S3 storage manager is separated and has to be created via corresponding object storage manager view - this will also allow for management of object storage without the need to have all the rest of services.

2. we allow for configuration of an advanced deployment via config files and utilities to bootstrap the environment. In the config we can allow for linking between regions and zones as well as specification of the services users are interested in. Users can always change this configuration and update the representation of the corresponding managers. For sure, there needs to be a super user doing this, but in large deployments, I assume this is always going to be the case.

I may be completely wrong on the matter in which case I apologise for introducing the noise 😄 .

**Comment by serenamarie125** [comment]
@blomquisg we don't have any bandwidth this week, could we touch base on Monday maybe and talk some things through ?

**Pull request closed without merging**
